# Generated by Django 4.2.9 on 2024-12-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_estanque', models.IntegerField()),
                ('tipo_estanque', models.CharField(choices=[('geomembrana', 'Geomembrana'), ('tierra', 'Tierra')], max_length=50)),
                ('profundidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('especie_pez', models.CharField(max_length=100)),
                ('cantidad_peces', models.IntegerField()),
                ('fecha_sembrado', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pendiente_verificacion', 'Pendiente Verificación')], max_length=50)),
                ('fecha_registro', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo_irregularidad', models.CharField(choices=[('calidad_agua', 'Calidad de Agua'), ('comportamiento_peces', 'Comportamiento de Peces'), ('equipamiento', 'Equipamiento')], max_length=50)),
                ('nivel_urgencia', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=50)),
                ('fecha_registro', models.DateTimeField()),
                ('id_estanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.estanque')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alimento', models.CharField(max_length=100)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('id_estanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.estanque')),
            ],
        ),
        migrations.AddField(
            model_name='estanque',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario'),
        ),
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alimento', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora', models.DateTimeField()),
                ('id_estanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.estanque')),
                ('id_historialactividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.historialactividad')),
                ('id_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.inventarioalimento')),
            ],
        ),
    ]
