# Generated by Django 4.2.9 on 2024-12-09 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_estanque_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
